# Generated by Django 5.2.14 on 2026-05-12 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('document_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField()),
                ('citation_order', models.IntegerField()),
            ],
            options={
                'db_table': 'citations',
                'ordering': ['citation_order'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('retrieval_score', models.FloatField(blank=True, null=True)),
                ('grounding_score', models.FloatField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('doc_ids', models.JSONField(default=list)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('chunk_count', models.IntegerField(default=0)),
                ('top_similarity_score', models.FloatField(blank=True, null=True)),
                ('grounding_score', models.FloatField(blank=True, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('model_used', models.CharField(default='gemini-2.0-flash', max_length=100)),
                ('low_confidence', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'query_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
